//! Localization infrastructure backed by `rust-i18n`.
//!
//! Translation files live in `crates/tokenx/locales/` as one file pair per
//! module scope: `<scope>.en.yml` and `<scope>.zh-CN.yml`. rust-i18n derives
//! the locale from the file stem's last dot segment and loads the v1 format:
//! nested keys WITHOUT a top-level locale wrapper, flattened to dot keys at
//! compile time (`cli:` → `error:` → `x` becomes `cli.error.x`). The `i18n!`
//! macro merges every YAML file in that directory, so scopes must not repeat
//! keys across files. `build.rs` tracks the directory so edits rebuild the
//! crate. See `crates/tokenx/AGENTS.md` for the key naming convention.
//!
//! The `rust_i18n::i18n!` macro itself is invoked once at the crate root in
//! `main.rs` (with `fallback = "en"`): the `t!` macro resolves a helper
//! generated by `i18n!` through `$crate`, so invoking it inside this module
//! would not compile.

use clap::ValueEnum;
use serde::{Deserialize, Serialize};

/// Scan raw process arguments for a valid language flag before Clap parses
/// them. This is intentionally conservative: malformed or unknown values are
/// ignored so the authoritative Clap parser can report them.
pub(crate) fn scan_cli_language<I, S>(args: I) -> Option<Language>
where
    I: IntoIterator<Item = S>,
    S: AsRef<std::ffi::OsStr>,
{
    let mut args = args.into_iter();
    args.next();

    while let Some(argument) = args.next() {
        let argument = argument.as_ref();
        if argument == std::ffi::OsStr::new("--") {
            break;
        }

        if let Some(value) = argument
            .to_str()
            .and_then(|argument| argument.strip_prefix("--language="))
        {
            if let Some(language) = parse_language_value(value) {
                return Some(language);
            }
            continue;
        }

        if argument != std::ffi::OsStr::new("--language") {
            continue;
        }

        let Some(value) = args.next() else {
            break;
        };
        let value = value.as_ref();
        if value == std::ffi::OsStr::new("--") {
            break;
        }
        if let Some(language) = value.to_str().and_then(parse_language_value) {
            return Some(language);
        }
    }

    None
}

fn parse_language_value(value: &str) -> Option<Language> {
    Language::from_str(value, false).ok()
}

/// Canonical interface languages accepted by `--language` and the
/// `language` settings key. Unknown spellings are hard parse errors in both
/// places; there is no silent fallback to English for a mistyped value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Serialize, Deserialize)]
pub(crate) enum Language {
    #[value(name = "en")]
    #[serde(rename = "en")]
    En,
    #[value(name = "zh-CN")]
    #[serde(rename = "zh-CN")]
    ZhCn,
}

impl Language {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::En => "en",

            Self::ZhCn => "zh-CN",
        }
    }
}

/// Resolve the active locale with the documented priority:
/// CLI flag > settings value > environment (`LC_ALL`, then `LANG`) > English.
pub(crate) fn resolve_locale(cli: Option<Language>, settings: Option<Language>) -> &'static str {
    if let Some(language) = cli {
        return language.as_str();
    }
    if let Some(language) = settings {
        return language.as_str();
    }
    detect_env_locale()
}

/// Set the process locale from the same priority chain as [`resolve_locale`].
pub(crate) fn init(cli: Option<Language>, settings: Option<Language>) {
    rust_i18n::set_locale(resolve_locale(cli, settings));
}

fn detect_env_locale() -> &'static str {
    detect_env_locale_from(
        std::env::var("LC_ALL").ok().as_deref(),
        std::env::var("LANG").ok().as_deref(),
    )
}

/// Pure core of [`detect_env_locale`]: the first non-empty variable wins,
/// and any value starting with `zh` (e.g. `zh_CN.UTF-8`) maps to `zh-CN`;
/// everything else maps to English.
fn detect_env_locale_from(lc_all: Option<&str>, lang: Option<&str>) -> &'static str {
    for value in [lc_all, lang].into_iter().flatten() {
        let value = value.trim();
        if value.is_empty() {
            continue;
        }
        return if value.to_ascii_lowercase().starts_with("zh") {
            Language::ZhCn.as_str()
        } else {
            Language::En.as_str()
        };
    }
    Language::En.as_str()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scans_valid_language_forms_before_and_after_subcommands() {
        assert_eq!(
            scan_cli_language(["tokenx", "--language", "zh-CN", "models"]),
            Some(Language::ZhCn)
        );
        assert_eq!(
            scan_cli_language(["tokenx", "models", "--language=zh-CN"]),
            Some(Language::ZhCn)
        );
        assert_eq!(
            scan_cli_language(["tokenx", "tui", "--language=en"]),
            Some(Language::En)
        );
    }

    #[test]
    fn scan_ignores_invalid_values_and_stops_at_separator() {
        assert_eq!(
            scan_cli_language(["tokenx", "--language", "unknown", "models"]),
            None
        );
        assert_eq!(
            scan_cli_language(["tokenx", "--language=unknown", "models"]),
            None
        );
        assert_eq!(
            scan_cli_language(["tokenx", "--", "--language", "zh-CN"]),
            None
        );
    }

    #[test]
    fn cli_language_wins_over_settings_and_environment() {
        assert_eq!(
            resolve_locale(Some(Language::ZhCn), Some(Language::En)),
            "zh-CN"
        );
        assert_eq!(resolve_locale(Some(Language::En), None), "en");
    }

    #[test]
    fn settings_language_wins_when_cli_is_absent() {
        assert_eq!(resolve_locale(None, Some(Language::ZhCn)), "zh-CN");
    }

    #[test]
    fn lc_all_takes_priority_over_lang() {
        assert_eq!(
            detect_env_locale_from(Some("zh_CN.UTF-8"), Some("en_US.UTF-8")),
            "zh-CN"
        );
        assert_eq!(detect_env_locale_from(None, Some("zh_TW")), "zh-CN");
    }

    #[test]
    fn empty_and_non_chinese_env_values_resolve_to_english() {
        assert_eq!(detect_env_locale_from(Some(""), Some("  ")), "en");
        assert_eq!(detect_env_locale_from(Some("C"), None), "en");
        assert_eq!(detect_env_locale_from(Some(""), Some("ja_JP.UTF-8")), "en");
        assert_eq!(detect_env_locale_from(None, None), "en");
    }

    #[test]
    fn any_zh_prefixed_env_value_maps_to_simplified_chinese() {
        for value in ["zh", "zh_CN.UTF-8", "zh-Hans-CN", "ZH_cn"] {
            assert_eq!(
                detect_env_locale_from(None, Some(value)),
                "zh-CN",
                "env value `{value}`"
            );
        }
    }

    #[test]
    fn language_round_trips_through_canonical_strings() {
        assert_eq!(Language::En.as_str(), "en");
        assert_eq!(Language::ZhCn.as_str(), "zh-CN");
        assert_eq!(
            serde_json::from_str::<Language>(r#""zh-CN""#).unwrap(),
            Language::ZhCn
        );
        assert!(serde_json::from_str::<Language>(r#""zh""#).is_err());
    }

    #[test]
    fn locale_files_from_multiple_scope_files_are_merged() {
        // Keys from `*.cli.yml` and `*.shared.yml` must both resolve; this is
        // what guarantees the one-file-pair-per-scope convention loads.
        assert_eq!(
            rust_i18n::t!("cli.error.tui_tab_disabled", locale = "en"),
            "TUI tab `subscription` is disabled in settings.json"
        );
        assert_eq!(
            rust_i18n::t!(
                "shared.client.invalid_id",
                locale = "zh-CN",
                raw = "nope",
                valid_ids = "claude"
            ),
            "无效的客户端 ID `nope`；可选值：claude"
        );
    }

    #[test]
    fn interpolation_fills_parameters_in_both_languages() {
        assert_eq!(
            rust_i18n::t!(
                "cli.error.reversed_date_range",
                locale = "en",
                since = "2024-12-31",
                until = "2024-01-01"
            ),
            "--since (2024-12-31) must not be later than --until (2024-01-01)"
        );
        assert_eq!(
            rust_i18n::t!(
                "cli.error.reversed_date_range",
                locale = "zh-CN",
                since = "2024-12-31",
                until = "2024-01-01"
            ),
            "--since（2024-12-31）不能晚于 --until（2024-01-01）"
        );
    }

    #[test]
    fn unsupported_locale_falls_back_to_english() {
        assert_eq!(
            rust_i18n::t!("cli.error.tui_tab_disabled", locale = "fr"),
            "TUI tab `subscription` is disabled in settings.json"
        );
    }
}
